## Basic Tutorials

In [ ]:
import numpy as np

In [ ]:
a = np.arange(0.0, 20.0, 1.0)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [ ]:
b = np.linspace(0.0, 19.0, 20)
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [ ]:
a.resize(4, 5)
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [ ]:
a[0]

array([0., 1., 2., 3., 4.])

In [ ]:
a[3]

array([15., 16., 17., 18., 19.])

In [ ]:
a[1, 4]

9.0

In [ ]:
a[1, 2:4]

array([7., 8.])

In [ ]:
a * 0.5

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [ ]:
a ** 2

array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.]])

In [ ]:
a + a

array([[ 0.,  2.,  4.,  6.,  8.],
       [10., 12., 14., 16., 18.],
       [20., 22., 24., 26., 28.],
       [30., 32., 34., 36., 38.]])

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
b = np.arange(0, 100.0, 1)
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [ ]:
for i in range(100):
    if b[i] == 50:
        print(f"50.0 at index no. {i}")

50.0 at index no. 50


In [ ]:
b = np.random.standard_normal((4, 5))
b

array([[ 1.04661947, -2.74580268, -0.23831576,  1.46726018, -0.07000494],
       [-2.26411511, -0.27535097, -1.7358735 , -1.05681725,  0.69702617],
       [ 0.29719479,  0.83260564,  0.37660107,  1.22506173, -1.24452666],
       [-1.78818604,  0.24477713,  0.19981654,  0.06206548,  1.16206055]])

## CRR Model: Nested `for`-loops

In [ ]:
import math

# Option Parameters
S0 = 105.0 # initial index level
K = 100.0# strike price
T = 1. # call option maturity
r = 0.05 # constant short rate
vola = 0.25 # constant volatility factor of diffusion

# Time Parameters
M = 3 # time steps
dt = T / M # length of time interval
df = math.exp(-r * dt) # discount factor per time interval

# Binomial Parameters
u = math.exp(vola * math.sqrt(dt)) # up-movement
d = 1 / u # down-movement
q = (math.exp(r * dt) - d) / (u - d) # martingale (risk-neutral) probability

In [ ]:
import numpy as np
S = np.zeros((M + 1, M + 1), dtype="float") # index level array
S[0, 0] = S0
S

array([[105.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.]])

In [ ]:
# Hilpsch's versions
# z = 0
# for j in range(1, M + 1, 1):
#     z += 1
#     for i in range(z + 1):
#         S[i, j] = S[0, 0] * (u ** j) * (d ** (i * 2))
#         #print(i, j)
# S

In [ ]:
# Pritam's version
# z = 0
# for j in range(1, M + 1, 1):
#     z += 1
#     for i in range(z + 1):
#         S[i, j] = S[0, 0] * (u ** (j - i)) * (d ** i)
#         #print(i, j)
# S

In [ ]:
# Pritam's version -- Removing z
#z = 0
for j in range(1, M + 1, 1):
    #z += 1
    for i in range(j + 1):
        S[i, j] = S[0, 0] * (u ** (j - i)) * (d ** i)
        #print(i, j)
S

array([[105.        , 121.30377267, 140.13909775, 161.89905958],
       [  0.        ,  90.88752771, 105.        , 121.30377267],
       [  0.        ,   0.        ,  78.67183517,  90.88752771],
       [  0.        ,   0.        ,   0.        ,  68.09798666]])

In [ ]:
# Array Initialization for Inner Values - Hilpsch's versions
# iv = np.zeros((M + 1, M + 1), dtype='float') # inner value array
# z = 0
# for j in range(0, M + 1, 1):
#     for i in range(z + 1):
#         iv[i, j] = round(max(S[i, j] - K, 0), 8)
#     z += 1
# iv

In [ ]:
# Array Initialization for Inner Values - Pritam's Version (removing z)
iv = np.zeros((M + 1, M + 1), dtype='float') # inner value array
#z = 0
for j in range(0, M + 1, 1):
    for i in range(j + 1):
        iv[i, j] = round(max(S[i, j] - K, 0), 8)
    #z += 1
iv

array([[ 5.        , 21.30377267, 40.13909775, 61.89905958],
       [ 0.        ,  0.        ,  5.        , 21.30377267],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [ ]:
# Valuation by Risk-Neutral Discounting - Hilpsch versions
# pv = np.zeros((M + 1, M + 1), dtype='float') # present value array
# pv[:, M] = iv[:, M] # initialize last time step
# z = M + 1
# for j in range(M - 1, -1, -1):
#     z -= 1
#     for i in range(z):
#         pv[i, j] = (q * pv[i, j + 1] + (1 - q) * pv[i + 1, j + 1]) * df
# pv

In [ ]:
# Valuation by Risk-Neutral Discounting - Pritam's version (don't need the inner-values array, getting rid of z)
pv = np.zeros((M + 1, M + 1), dtype='float') # present value array
#pv[:, M] = iv[:, M] # initialize last time step
pv[:, M] = np.maximum(S[:, M] - K, 0)
#z = M + 1
for j in range(M - 1, -1, -1):
    #z -= 1
    for i in range(j + 1):
        pv[i, j] = (q * pv[i, j + 1] + (1 - q) * pv[i + 1, j + 1]) * df
pv

array([[16.29293245, 26.59599847, 41.79195237, 61.89905958],
       [ 0.        ,  5.61452766, 10.93666406, 21.30377267],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [ ]:
# for j in range(M - 1, -1, -1):
#     print(j)

In [ ]:
# for j in range(M - 1, -1, -1):
#     print(j)

In [ ]:
print(pv[0,0])

16.29293244989886


## CRR Model: Vectorized Code

In [ ]:
mu = np.arange(M + 1)
mu

array([0, 1, 2, 3])

In [ ]:
mu = np.resize(mu, (M + 1, M + 1))
mu

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
md = mu.T
md

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [ ]:
mu = u ** (mu - md)
mu

array([[1.        , 1.15527403, 1.33465807, 1.54189581],
       [0.8655955 , 1.        , 1.15527403, 1.33465807],
       [0.74925557, 0.8655955 , 1.        , 1.15527403],
       [0.64855225, 0.74925557, 0.8655955 , 1.        ]])

In [ ]:
md = d ** md
md

array([[1.        , 1.        , 1.        , 1.        ],
       [0.8655955 , 0.8655955 , 0.8655955 , 0.8655955 ],
       [0.74925557, 0.74925557, 0.74925557, 0.74925557],
       [0.64855225, 0.64855225, 0.64855225, 0.64855225]])

In [ ]:
S = S0 * mu * md
S

array([[105.        , 121.30377267, 140.13909775, 161.89905958],
       [ 78.67183517,  90.88752771, 105.        , 121.30377267],
       [ 58.94531095,  68.09798666,  78.67183517,  90.88752771],
       [ 44.16510274,  51.02279602,  58.94531095,  68.09798666]])

In [ ]:
S = np.triu(S) # set the entries below the diagonal equal to zero
S

array([[105.        , 121.30377267, 140.13909775, 161.89905958],
       [  0.        ,  90.88752771, 105.        , 121.30377267],
       [  0.        ,   0.        ,  78.67183517,  90.88752771],
       [  0.        ,   0.        ,   0.        ,  68.09798666]])

In [ ]:
# Valuation by Risk-Neutral Discounting
pv = np.maximum(S - K, 0) # present value array initialized with inner values
z = 0
for i in range(M - 1, -1, -1): # backwards induction
    pv[0:M - z, i] = (q * pv[0:M - z, i + 1]
                    + (1 - q) * pv[1:M - z + 1, i + 1]) * df
    z += 1

# Result Output
print(pv[0, 0])

16.29293244989886


## cantaro86

In [ ]:
S0 = 105.0  # spot stock price
K = 100.0  # strike
T = 1.0  # maturity
r = 0.05  # risk free rate
sig = 0.25  # diffusion coefficient or volatility

N = 3  # number of periods or number of time steps
payoff = "call"  # payoff

In [ ]:
dT = float(T) / N  # Delta t
u = np.exp(sig * np.sqrt(dT))  # up factor
d = 1.0 / u  # down factor

In [ ]:
V = np.zeros(N + 1)  # initialize the price vector
V

array([0., 0., 0., 0.])

In [ ]:
S_T = np.array([(S0 * u**j * d ** (N - j)) for j in range(N + 1)])  # price S_T at time T
S_T

array([ 68.09798666,  90.88752771, 121.30377267, 161.89905958])

In [ ]:
a = np.exp(r * dT)  # risk free compound return
p = (a - d) / (u - d)  # risk neutral up probability
q = 1.0 - p  # risk neutral down probability

In [ ]:
if payoff == "call":
    V[:] = np.maximum(S_T - K, 0.0)
elif payoff == "put":
    V[:] = np.maximum(K - S_T, 0.0)
V

array([ 0.        ,  0.        , 21.30377267, 61.89905958])

In [ ]:
for i in range(N - 1, -1, -1):
    V[:-1] = np.exp(-r * dT) * (p * V[1:] + q * V[:-1])  # the price vector is overwritten at each step
    S_T = S_T * u  # it is a tricky way to obtain the price at the previous time step
    if payoff == "call":
        V = np.maximum(V, S_T - K)
    elif payoff == "put":
        V = np.maximum(V, K - S_T)
V

array([ 16.29293245,  45.52726404,  89.83292357, 149.6314809 ])

In [ ]:
print("American BS Tree Price: ", V[0])

American BS Tree Price:  16.29293244989886


## quantpy

In [ ]:
# Initialise parameters
S0 = 105      # initial stock price
K = 100       # strike price
T = 1         # time to maturity in years
r = 0.05      # annual risk-free rate
N = 3        # number of time steps
sig = 0.25
dt = T / N
u = np.exp(sig * np.sqrt(dt))  # up factor
d = 1.0 / u  # down factor
# u = 1.1       # up-factor in binomial models
# d = 1/u       # ensure recombining tree
opttype = 'C' # Option Type 'C' or 'P'

In [ ]:
def american_fast_tree(K,T,S0,r,N,u,d,opttype='P'):
    #precompute values
    dt = T/N
    q = (np.exp(r*dt) - d)/(u-d)
    disc = np.exp(-r*dt)
    
    # initialize stock prices at maturity
    S = S0 * d**(np.arange(N,-1,-1)) * u**(np.arange(0,N+1,1))
        
    # option payoff 
    if opttype == 'P':
        C = np.maximum(0, K - S)
    else:
        C = np.maximum(0, S - K)
    
    # backward recursion through the tree
    for i in np.arange(N-1,-1,-1):
        #S = S0 * d**(np.arange(i,-1,-1)) * u**(np.arange(0,i+1,1))
        S = (S * u)[0:-1]
        #C[:i+1] = disc * ( q*C[1:i+2] + (1-q)*C[0:i+1] )
        #C = C[:-1]
        C =  disc * ( q*C[1:i+2] + (1-q)*C[0:i+1] )
        if opttype == 'P':
            C = np.maximum(C, K - S)
        else:
            C = np.maximum(C, S - K)
                
    return C[0]
american_fast_tree(K,T,S0,r,N,u,d,opttype)

16.292932449898853

## quantpy - step by step

In [ ]:
# Initialize parameters
S0 = 105      # initial stock price
K = 100       # strike price
T = 1         # time to maturity in years
r = 0.05      # annual risk-free rate
N = 3         # number of time steps
sig = 0.25
dt = T / N
u = np.exp(sig * np.sqrt(dt))  # up factor
d = 1.0 / u  # down factor
opttype = 'C' # Option Type 'C' or 'P'

In [ ]:
q = (np.exp(r*dt) - d)/(u-d)
disc = np.exp(-r*dt)

In [ ]:
# terminal underlying values
S = S0 * (d**np.arange(N, -1, -1)) * (u**np.arange(0, N+1, 1))

In [ ]:
# option payoff at expiration
if opttype == 'P':
    C = np.maximum(0, K - S)
else:
    C = np.maximum(0, S - K)

In [ ]:
# for i in np.arange(N-1,-1,-1):
#     S = (S * u)[:-1]
#     print(S)

In [ ]:
# backward recursion through the tree
for i in np.arange(N-1,-1,-1):
    #S = S0 * d**(np.arange(i,-1,-1)) * u**(np.arange(0,i+1,1))
    S = (S * u)[0:-1]
    #C[:i+1] = disc * ( q*C[1:i+2] + (1-q)*C[0:i+1] )
    #C = C[:-1]
    C =  disc * (q*C[1:i+2] + (1-q)*C[0:i+1])
    print(C)
    if opttype == 'P':
        C = np.maximum(C, K - S)
    else:
        C = np.maximum(C, S - K)

[ 0.         10.93666406 41.79195237]
[ 5.61452766 26.59599847]
[16.29293245]
